2019-05-17 15:42:15,948 - root - ERROR -f app.py -m Traceback (most recent call last):
  File "/Users/gring2/workspace/bookMarkLibrary/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gring2/workspace/bookMarkLibrary/venv/lib/python3.7/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/gring2/workspace/bookMarkLibrary/venv/lib/python3.7/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/Users/gring2/workspace/bookMarkLibrary/venv/lib/python3.7/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/Users/gring2/workspace/bookMarkLibrary/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

